---
title: "01-Data"
output: html_document
date: "2025-09-30"
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(dplyr)
library(lubridate) 
library(cricketdata)

odis_match <- fetch_cricsheet(type = "match", gender = "male", competition = "odis") 
odi_bbb <- fetch_cricsheet(type = "bbb", gender = "male", competition = "odis")

# Ensure both match_id are the same type (character is safer)

odi_bbb <- odi_bbb %>% 
  mutate(start_date = as.Date(start_date), match_id = as.character(match_id))

odis_meta <- odis_match %>%
  mutate(match_id = as.character(match_id)) %>% 
  select(match_id, winner, toss_winner, toss_decision, team1, team2, date, venue)

# Filter 2015 onwards and join

odi_bbb_recent <- odi_bbb %>% 
  filter(start_date >= as.Date("2015-01-01")) %>% 
  left_join(odis_meta, by = "match_id")%>%
  left_join(player_meta[c("unique_name", "bowling_style")], by = join_by("bowler"=="unique_name"), relationship = "many-to-many")%>%
  left_join(player_meta[c("unique_name", "batting_style")], by = join_by("striker"=="unique_name"), relationship = "many-to-many")

if (!require("fs")) install.packages("fs")
library(fs)

processed_file <- path_wd("..", "data", "processed", "odi_bbb_recent.csv")

write.csv(odi_bbb_recent, file = processed_file, row.names = FALSE)

```
